### ISSUE TITLE
Remove sensitive data

### ISSUE THREAD

**Issue by rafaelsilverioit** [yants95/twitter_clone#1]
Do not post sensitive data to control version systems, never, ever.
Remove it from here: [index.js](https://github.com/yants95/twitter_clone/blob/master/backend/src/index.js)

**Comment by rafaelsilverioit** [comment]
Also, remove it from git commit history.

**Comment by yants95** [comment]
> Do not post sensitive data to control version systems, never, ever.
> Remove it from here: [index.js](https://github.com/yants95/twitter_clone/blob/master/backend/src/index.js)

Although it was a test I appreciate your advice!

Solved.
